<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "templates"
 *
 * Auto generated by Extension Builder 2014-12-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['templates'] = array(
	'title' => 'templates',
	'description' => 'Aimeos TYPO3 extension for templates project',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '10.4.0-11.99.99',
			'aimeos' => '22.4.0-22.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
